/**
 * namelessJoinRequestFixture.ts — a narrow, documented exception to CLAUDE.md's
 * e2e rule "publish through the app, never raw WebSocket" (epic:
 * invite-rescind-and-member-removal, story S11 — AC-SCEN-2).
 *
 * Mirrors the ONE existing documented exception, forgedPairingAck.ts
 * (epic: contact-pairing-code, S6): same rationale shape, same mechanism
 * (build the real wire event with nostr-tools/nip59 directly — the exact
 * library the app itself uses — then publish it via a single raw WebSocket
 * frame inside `page.evaluate` on a REAL browser page).
 *
 * WHY this exception is necessary: AC-SCEN-2 requires a join request whose
 * `requesterName` field is genuinely absent (joinRequestStorage's optional
 * `nickname` ends up `undefined` — the "older client that doesn't send the
 * field" tolerance documented on `PendingJoinRequest.nickname`). The app's
 * OWN current UI (`JoinRequestCard.tsx`) makes this structurally
 * unproducible through a real button click: `isJoinRequestDisabled` /
 * `isWelcomeJoinRequestDisabled` both hard-gate on `hasShareableName`,
 * disabling the Send button until a non-blank name is entered. There is no
 * form, deep link, or code path that lets a real user submit a join request
 * with a blank name — exactly the "events the app cannot itself produce"
 * carve-out CLAUDE.md's E2E section names, and exactly the shape
 * forgedPairingAck.ts already established precedent for.
 *
 * WHAT stays real, what is spoofed: the gift wrap is built with
 * nostr-tools/nip59's own `wrapEvent` (the same call
 * `joinRequestSender.ts#buildGiftWrap` makes), driven by the requester's
 * OWN real private key — a genuine, validly-signed, correctly-addressed
 * event. The only thing this fixture does that the UI cannot is omit
 * `requesterName` from the rumor's JSON content (by never including the key
 * at all, so `JSON.stringify` drops it — byte-identical to what
 * `buildJoinRequestRumor` itself produces when its own `requesterName`
 * parameter is `undefined`). No identity is spoofed, no unauthenticated
 * write occurs, and no other part of this scenario (join-link generation,
 * approval, subsequent member-list rendering) bypasses the app.
 *
 * The kind number (21059) is duplicated here as a plain literal rather than
 * imported from `@/src/lib/marmot/joinRequestSender` — this repo's
 * established test/production import boundary (see forgedPairingAck.ts's
 * own PAIRING_ACK_KIND comment for the identical precedent).
 */
import type { Page } from '@playwright/test';

const RELAY_URL = process.env.E2E_RELAY_URL ?? 'ws://localhost:7777';

/** Duplicated from joinRequestSender.ts's JOIN_REQUEST_RUMOR_KIND (kind 21059). */
const JOIN_REQUEST_RUMOR_KIND = 21059;

export type NamelessJoinRequestParams = {
  /** The requester's own REAL private key hex — the gift wrap is genuinely, validly signed by this identity. */
  requesterPrivateKeyHex: string;
  /** The requester's own REAL pubkey hex (derived from requesterPrivateKeyHex) — what the rumor/seal will authenticate as. */
  requesterPubkeyHex: string;
  /** The admin's pubkey hex the invite link names (recipient of the gift wrap). */
  adminPubkeyHex: string;
  /** The invite link's nonce, as parsed from the real `?join=` query param generated by the app. */
  nonce: string;
  /** The group's display name, as parsed from the real `?name=` query param. */
  groupName: string;
};

/**
 * Build (in this Node test process, via nostr-tools/nip59 directly) and
 * publish (via the requester's own real browser page, raw WebSocket) a join
 * request gift wrap whose inner rumor content omits `requesterName` entirely
 * — the one input shape the app's own UI structurally refuses to produce.
 * See the file header for the full rationale.
 */
export async function sendNamelessJoinRequest(page: Page, params: NamelessJoinRequestParams): Promise<void> {
  const { wrapEvent } = await import('nostr-tools/nip59');
  const { getPublicKey } = await import('nostr-tools/pure');

  const privBytes = hexToBytes(params.requesterPrivateKeyHex);

  // Sanity self-check: refuse to publish a mismatched fixture (mirrors
  // forgedPairingAck.ts's identical guard and joinRequestSender.ts#sendJoinRequest's
  // own runtime check of the same invariant).
  const derivedPubkeyHex = getPublicKey(privBytes);
  if (derivedPubkeyHex.toLowerCase() !== params.requesterPubkeyHex.toLowerCase()) {
    throw new Error(
      '[namelessJoinRequestFixture] requesterPubkeyHex does not match the pubkey derived from requesterPrivateKeyHex — refusing to publish a mismatched fixture',
    );
  }

  // Byte-identical shape to buildJoinRequestRumor's content, EXCEPT
  // requesterName is never included as a key (JSON.stringify drops an
  // explicit `undefined` value the same way it would an omitted property).
  const content = JSON.stringify({
    type: 'join_request',
    nonce: params.nonce,
    name: params.groupName,
    requesterName: undefined,
  });

  const wrap = wrapEvent(
    {
      kind: JOIN_REQUEST_RUMOR_KIND,
      content,
      tags: [['p', params.adminPubkeyHex]],
      created_at: Math.floor(Date.now() / 1000),
    },
    privBytes,
    params.adminPubkeyHex,
  );

  await page.evaluate(
    ({ relayUrl, event }) => {
      return new Promise<void>((resolve, reject) => {
        const ws = new WebSocket(relayUrl);
        let settled = false;
        const done = (err?: Error) => {
          if (settled) return;
          settled = true;
          try {
            ws.close();
          } catch {
            /* ignore */
          }
          if (err) reject(err);
          else resolve();
        };
        const timeout = setTimeout(() => done(), 8_000);
        ws.onopen = () => {
          ws.send(JSON.stringify(['EVENT', event]));
        };
        ws.onmessage = (msg) => {
          try {
            const data = JSON.parse(msg.data as string);
            if (data[0] === 'OK' && data[1] === event.id) {
              clearTimeout(timeout);
              done();
            }
          } catch {
            /* ignore parse errors */
          }
        };
        ws.onerror = () => {
          clearTimeout(timeout);
          done(new Error('[namelessJoinRequestFixture] relay publish WebSocket error'));
        };
      });
    },
    { relayUrl: RELAY_URL, event: wrap },
  );
}

function hexToBytes(hex: string): Uint8Array {
  const bytes = new Uint8Array(hex.length / 2);
  for (let i = 0; i < hex.length; i += 2) {
    bytes[i / 2] = parseInt(hex.slice(i, i + 2), 16);
  }
  return bytes;
}
