/**
 * E2E: `/groups/?join=` first-visit welcome screen — group-invite variant
 * (epic: first-visit-invite-welcome, story S4; AC-GROUP-1..4, AC-RETURN-2,
 * AC-PRIV-1/2, AC-NAME-1).
 *
 * A genuine first-time visitor (no identity seeded — the app auto-generates
 * one on mount, S1's `isFreshIdentity`) who opens a real group invite link
 * sees the blended `WelcomeInvite` screen (hosting the existing name gate +
 * "Request to Join" action inline) instead of today's bare join card, with
 * no separate join card shown afterward. A returning user (identity already
 * on disk) keeps today's bare join-card behavior unchanged (AC-RETURN-2).
 *
 * Superseded note (epic: invite-link-awaiting-landing, S3, 2026-07-19): the
 * AC-RETURN-2 describe block below's two returning-user tests now assert
 * `invite-awaiting-banner` (and, for the nameless variant,
 * `invite-awaiting-name-input` / `invite-awaiting-request-btn`) instead of
 * the bare `join-request-card` / `join-request-name-gate` / `join-request-
 * name-input` / `join-request-send-btn` testids described below — a
 * returning user opening a group invite link now lands on the groups LIST
 * view with that banner, not the full-page join card. The tests' actual
 * intent (a returning user never gets the first-timer WELCOME screen, and
 * can still complete a gated request) is unchanged; only the surface it's
 * asserted against moved. The first-time-visitor describe blocks above and
 * below this one are untouched by that epic and still exercise
 * `join-request-card`/`welcome-invite` exactly as documented here.
 *
 * This spec needs the groups/relay Docker bucket: the invite link is
 * generated by a real admin peer through the app's own
 * GenerateInviteLinkModal (never a hand-built URL), and the incoming join
 * request is observed on the admin's side as a real NIP-59 gift-wrap
 * received over the relay — never a raw WebSocket publish from test code
 * (CLAUDE.md's "E2E tests must drive publishes through the app" rule).
 *
 * Remediation round (VQ-S4-016, VQ-S4-017 — post-impl questions raised by
 * the verification examiner):
 *  - VQ-S4-017: added a returning-but-NAMELESS variant (USER_C, no
 *    nickname) to the AC-RETURN-2 describe block below. The original
 *    AC-RETURN-2 test seeds a nickname for the returning user, so
 *    JoinRequestCard's OWN internal name gate (`gateActive` /
 *    `join-request-name-gate`) was never reached by this spec — only the
 *    `isFreshIdentity` branch was proven. The new variant proves the OLD
 *    inline name-gated path still renders (not `welcome-invite`) and still
 *    completes for a returning user with no saved name.
 *  - VQ-S4-016: added a deterministic send-failure test. `WelcomeInvite`
 *    has no error slot by design (S2), so `JoinRequestCard`'s welcome
 *    branch renders a standalone Chakra `Alert` (`role="alert"`) above it
 *    when `handleSendRequest`'s existing `error` state is set. The relay
 *    publish is forced to fail deterministically via
 *    `context.setOffline(true)` right before the click (no relay-dependent
 *    timing assumed — `rawPublish`'s own `ws.onerror`/10s-timeout fallback
 *    makes this deterministic either way, just possibly slower).
 */
import { test, expect, BrowserContext, Page } from '@playwright/test';
import { USER_A, USER_B, USER_C, computeTestKeypairs } from './helpers/auth-helpers';
import { clearAppState } from './helpers/clear-state';
import { dismissErrorOverlay, suppressErrorOverlay } from './helpers/dismiss-error-overlay';

const BASE_URL = process.env.BASE_URL || 'http://localhost:3100';

/** Boot a user context WITH a seeded identity — the admin path, and the
 *  returning-user (AC-RETURN-2) path. Mirrors groups-invite-link.spec.ts's
 *  bootUser. */
async function bootUser(
  browser: { newContext: (opts: object) => Promise<BrowserContext> },
  user: typeof USER_A,
  opts?: { nickname?: string },
): Promise<{ context: BrowserContext; page: Page }> {
  const context = await browser.newContext({ baseURL: BASE_URL });
  await suppressErrorOverlay(context);
  await context.addInitScript(({ privateKeyHex, pubkeyHex, seedHex, nickname }) => {
    localStorage.setItem('lp_nostrIdentity_v1', JSON.stringify({ privateKeyHex, pubkeyHex, seedHex }));
    if (nickname) {
      localStorage.setItem('lp_userProfile_v1', JSON.stringify({ nickname, avatar: null }));
    }
  }, { privateKeyHex: user.privateKeyHex, pubkeyHex: user.pubkeyHex, seedHex: user.seedHex, nickname: opts?.nickname ?? '' });
  const page = await context.newPage();
  await page.goto('/');
  await clearAppState(page);
  await page.reload();
  await page.goto('/groups/');
  await expect(
    page.getByTestId('groups-empty-state').or(page.getByTestId('groups-list')),
  ).toBeVisible({ timeout: 60_000 });
  return { context, page };
}

/**
 * Boot a COMPLETELY ANONYMOUS context — no identity, no profile seeded at
 * all. The app auto-generates an identity on first mount (S1's
 * `isFreshIdentity = true` for this load) — the genuine first-time-visitor
 * case this story targets. Mirrors add-welcome.spec.ts's
 * `newAnonymousContext`, re-declared locally because that helper's BASE_URL
 * default (contact-card.ts, non-relay bucket, port 3000) differs from this
 * spec's relay-bucket BASE_URL (port 3100).
 */
async function bootAnonymous(
  browser: { newContext: (opts: object) => Promise<BrowserContext> },
): Promise<{ context: BrowserContext; page: Page }> {
  const context = await browser.newContext({ baseURL: BASE_URL });
  await suppressErrorOverlay(context);
  const page = await context.newPage();
  return { context, page };
}

/** Create a group from the given (admin) page. */
async function createGroup(page: Page, name: string): Promise<void> {
  await page.getByTestId('create-group-btn').click();
  await expect(page.getByTestId('create-group-modal-content')).toBeVisible();
  await page.getByTestId('create-group-name-input').fill(name);
  await page.getByTestId('create-group-submit-btn').click();
  await expect(page.getByText(name)).toBeVisible({ timeout: 30_000 });
  await expect(page.getByTestId('create-group-modal-content')).not.toBeVisible({ timeout: 10_000 });
  await dismissErrorOverlay(page);
  await page.waitForTimeout(3_000);
}

/** Navigate to a group's detail page. */
async function openGroupDetail(page: Page, groupName: string): Promise<void> {
  await dismissErrorOverlay(page);
  await page.locator(`[data-testid^="group-card-"]`, { hasText: groupName }).click();
  await expect(page.getByTestId('group-detail-page')).toBeVisible({ timeout: 30_000 });
}

/** Generate a real invite link through the app's own UI and return it. */
async function generateInviteLink(page: Page, groupName: string): Promise<string> {
  await openGroupDetail(page, groupName);
  await page.getByTestId('invite-link-btn').click();
  await expect(page.getByTestId('generate-invite-link-modal')).toBeVisible();
  const urlElement = page.getByTestId('invite-link-url');
  await expect(urlElement).toBeVisible();
  const inviteUrl = (await urlElement.textContent()) ?? '';
  expect(inviteUrl).toContain('/groups/?join=');
  await page.getByTestId('invite-link-copy-btn').click();
  await page.waitForTimeout(1_000);
  await page.getByTestId('generate-invite-link-modal').locator('[aria-label="Close"]').click();
  await expect(page.getByTestId('generate-invite-link-modal')).not.toBeVisible({ timeout: 5_000 });
  return inviteUrl;
}

async function readSavedNickname(page: Page): Promise<string | null> {
  return page.evaluate(() => {
    try {
      const raw = localStorage.getItem('lp_userProfile_v1');
      return raw ? ((JSON.parse(raw) as { nickname: string }).nickname ?? null) : null;
    } catch {
      return null;
    }
  });
}

// ---------------------------------------------------------------------------
// AC-GROUP-1..4, AC-PRIV-1/2, AC-NAME-1: first-time visitor
// ---------------------------------------------------------------------------
test.describe.serial('Group-invite welcome screen — first-time visitor', () => {
  const GROUP_NAME = 'Welcome Screen Test Group';
  const INVITEE_NAME = 'Wanda Welcome';
  let ctxAdmin: BrowserContext;
  let ctxInvitee: BrowserContext;
  let pageAdmin: Page;
  let pageInvitee: Page;
  let inviteUrl = '';

  test.beforeAll(async ({ browser }) => {
    await computeTestKeypairs();
    ({ context: ctxAdmin, page: pageAdmin } = await bootUser(browser, USER_A, { nickname: 'Admin' }));
    ({ context: ctxInvitee, page: pageInvitee } = await bootAnonymous(browser));
  });

  test.afterAll(async () => {
    await ctxAdmin?.close();
    await ctxInvitee?.close();
  });

  test('Admin creates a group and generates a real invite link', async () => {
    await createGroup(pageAdmin, GROUP_NAME);
    inviteUrl = await generateInviteLink(pageAdmin, GROUP_NAME);
    await expect(pageAdmin.getByTestId('group-detail-page')).toBeVisible();
  });

  test('AC-GROUP-1/2/3, AC-PRIV-1/2: a fresh first-timer sees the blended welcome screen (not the bare join card) with the exact group name from the URL, gated on a name, and no public/kind-0 publish while merely rendering', async () => {
    // AC-PRIV-1/2: track every outgoing WS frame across the whole flow
    // (render through submit) and assert no kind-0 (public profile) event is
    // EVER published. Mirrors add-welcome.spec.ts's identical pattern: the
    // app legitimately opens relay connections for unrelated reasons (e.g. a
    // KeyPackage publish) on every identity mount, so "zero connections" is
    // not the invariant — "never a kind-0 EVENT" is.
    let kind0EventPublished = false;
    pageInvitee.on('websocket', (ws) => {
      ws.on('framesent', (frame) => {
        try {
          const text = typeof frame.payload === 'string' ? frame.payload : frame.payload.toString('utf-8');
          const data: unknown = JSON.parse(text);
          if (Array.isArray(data) && data[0] === 'EVENT' && (data[1] as { kind?: number })?.kind === 0) {
            kind0EventPublished = true;
          }
        } catch {
          // Non-JSON/non-EVENT frames (PING/AUTH/etc.) are irrelevant here.
        }
      });
    });

    const url = new URL(inviteUrl);
    const pathWithQuery = url.pathname + url.search;
    await pageInvitee.goto(pathWithQuery);
    await dismissErrorOverlay(pageInvitee);

    // AC-GROUP-1 / VQ-S4-007: the welcome screen renders, hosting the name
    // field + action inline — NOT the bare join card. Only one join-related
    // testid tree exists on the page at a time.
    await expect(pageInvitee.getByTestId('welcome-invite')).toBeVisible({ timeout: 30_000 });
    await expect(pageInvitee.getByTestId('join-request-card')).toHaveCount(0);

    // AC-GROUP-2: the invite line shows the EXACT group name from the URL's
    // name param (not a generic placeholder).
    await expect(pageInvitee.getByTestId('welcome-invite-line')).toHaveText(`You're invited to join ${GROUP_NAME}`);

    // AC-PRIV-2: rendering alone (a URL-only read, no relay query) cannot
    // have published anything by this point.
    expect(kind0EventPublished).toBe(false);

    // AC-GROUP-3 / VQ-S4-009: the join action is disabled until a non-blank
    // name, reactive to typing/clearing — the same shared predicate proven
    // for the contact variant (AC-CONTACT-5).
    const action = pageInvitee.getByTestId('welcome-primary-action');
    await expect(action).toBeDisabled();
    const nameInput = pageInvitee.getByTestId('welcome-name-input');
    await nameInput.fill(INVITEE_NAME);
    await expect(action).toBeEnabled();
    await nameInput.fill('');
    await expect(action).toBeDisabled();
    await nameInput.fill(INVITEE_NAME);
    await expect(action).toBeEnabled();

    // AC-GROUP-4: pressing the action saves the name, sends the real join
    // request via the existing send path, then shows the existing
    // confirmation. The welcome screen itself is gone afterward — no
    // separate join card ever appears (AC-GROUP-1).
    await action.click();
    await expect(pageInvitee.getByTestId('join-request-sent')).toBeVisible({ timeout: 30_000 });
    await expect(pageInvitee.getByTestId('welcome-invite')).toHaveCount(0);
    await expect(pageInvitee.getByTestId('join-request-card')).toHaveCount(0);

    // AC-NAME-1: the entered name persisted to the local profile (observable
    // state, not just the confirmation UI).
    await expect.poll(() => readSavedNickname(pageInvitee)).toBe(INVITEE_NAME);

    // AC-PRIV-1: across the FULL flow — render, name entry, saveProfile, and
    // the gift-wrapped join request — no public profile broadcast was ever
    // sent.
    expect(kind0EventPublished).toBe(false);
  });

  test("Admin observes the incoming join request with the newcomer's real name — proves a real gift-wrapped request was sent, not a UI-only confirmation (VQ-S4-010)", async () => {
    await pageAdmin.goto('/groups/');
    await expect(
      pageAdmin.getByTestId('groups-empty-state').or(pageAdmin.getByTestId('groups-list')),
    ).toBeVisible({ timeout: 60_000 });

    await expect
      .poll(
        async () => {
          await dismissErrorOverlay(pageAdmin);
          const badge = pageAdmin.getByTestId('notification-badge').first();
          return badge.isVisible();
        },
        { timeout: 60_000, intervals: [3_000, 5_000, 5_000, 5_000, 5_000, 5_000, 5_000] },
      )
      .toBe(true);

    await openGroupDetail(pageAdmin, GROUP_NAME);
    await expect(
      pageAdmin.locator('[data-testid^="pending-request-row-"]').filter({ hasText: INVITEE_NAME }),
    ).toBeVisible({ timeout: 30_000 });
  });
});

// ---------------------------------------------------------------------------
// AC-RETURN-2: returning user
// ---------------------------------------------------------------------------
test.describe('Group-invite welcome screen — returning user (AC-RETURN-2)', () => {
  const GROUP_NAME = 'Welcome Screen Returning-User Group';

  test('a returning user (identity already on disk) opening a group invite link gets the pre-existing bare join card, never the welcome screen', async ({ browser }) => {
    await computeTestKeypairs();
    const { context: ctxAdmin, page: pageAdmin } = await bootUser(browser, USER_A, { nickname: 'Admin' });
    // Returning visitor: identity ALREADY seeded (bootUser) — isFreshIdentity
    // is false for this load, so today's pre-S4 behavior applies unchanged
    // (VQ-S4-011).
    const { context: ctxReturning, page: pageReturning } = await bootUser(browser, USER_B, { nickname: 'Returning Bob' });

    try {
      await createGroup(pageAdmin, GROUP_NAME);
      const inviteUrl = await generateInviteLink(pageAdmin, GROUP_NAME);

      const url = new URL(inviteUrl);
      const pathWithQuery = url.pathname + url.search;
      await pageReturning.goto(pathWithQuery);
      await dismissErrorOverlay(pageReturning);

      // epic: invite-link-awaiting-landing (S3) supersedes the bare
      // full-screen join card for a returning user: this branch now renders
      // InviteAwaitingBanner on the groups list instead. The test's actual
      // intent (a returning user never gets the first-timer WELCOME screen)
      // still holds unchanged below.
      await expect(pageReturning.getByTestId('invite-awaiting-banner')).toBeVisible({ timeout: 30_000 });
      await expect(pageReturning.getByTestId('welcome-invite')).toHaveCount(0);
    } finally {
      await ctxAdmin.close();
      await ctxReturning.close();
    }
  });

  test('VQ-S4-017: a returning-but-NAMELESS user (identity already on disk, no saved nickname) still gets the OLD inline name gate — not the welcome screen — and can complete the request through it', async ({ browser }) => {
    await computeTestKeypairs();
    const NAMELESS_GROUP_NAME = 'Welcome Screen Returning-Nameless-User Group';
    const REQUEST_NAME = 'Returning Nameless Nadia';
    const { context: ctxAdmin, page: pageAdmin } = await bootUser(browser, USER_A, { nickname: 'Admin' });
    // Returning (identity already on disk, so isFreshIdentity is false — the
    // isFreshIdentity branch is NOT what renders here) AND nameless (no
    // `nickname` option, so hasShareableName('') is false) — the ONE
    // combination the other AC-RETURN-2 test above cannot reach because it
    // seeds 'Returning Bob' for USER_B. This exercises JoinRequestCard's OWN
    // pre-existing `gateActive` / `join-request-name-gate` branch, distinct
    // from groups-invite-link.spec.ts's nameless-invitee coverage (USER_C
    // there too, but that spec never touches isFreshIdentity at all).
    const { context: ctxReturning, page: pageReturning } = await bootUser(browser, USER_C);

    try {
      await createGroup(pageAdmin, NAMELESS_GROUP_NAME);
      const inviteUrl = await generateInviteLink(pageAdmin, NAMELESS_GROUP_NAME);

      const url = new URL(inviteUrl);
      const pathWithQuery = url.pathname + url.search;
      await pageReturning.goto(pathWithQuery);
      await dismissErrorOverlay(pageReturning);

      // epic: invite-link-awaiting-landing (S3) supersedes the bare
      // full-screen join card for a returning user: InviteAwaitingBanner
      // renders instead — never the first-timer welcome variant.
      await expect(pageReturning.getByTestId('invite-awaiting-banner')).toBeVisible({ timeout: 30_000 });
      await expect(pageReturning.getByTestId('welcome-invite')).toHaveCount(0);

      // The inline name gate is present (nameless returning user) and gates
      // the request button, reactive to typing — same predicate/UI proven
      // nameless-first-timer-side by groups-invite-link.spec.ts's AC-GATE-1..3.
      const nameInput = pageReturning.getByTestId('invite-awaiting-name-input');
      await expect(nameInput).toBeVisible();
      await expect(nameInput).toHaveValue('');
      const sendBtn = pageReturning.getByTestId('invite-awaiting-request-btn');
      await expect(sendBtn).toBeDisabled();

      await nameInput.fill(REQUEST_NAME);
      await expect(sendBtn).toBeEnabled();

      // The request completes through the banner's path — proves the gate
      // isn't just cosmetically present but still functionally wired end to
      // end.
      await sendBtn.click();
      const nonce = url.searchParams.get('join');
      expect(nonce).toBeTruthy();
      await expect(pageReturning.getByTestId(`outbound-request-card-${nonce!.slice(0, 6)}`)).toBeVisible({ timeout: 30_000 });
    } finally {
      await ctxAdmin.close();
      await ctxReturning.close();
    }
  });
});

// ---------------------------------------------------------------------------
// VQ-S4-016: send-failure error path on the welcome (first-timer) variant
// ---------------------------------------------------------------------------
test.describe('Group-invite welcome screen — send failure surfaces the error Alert (VQ-S4-016)', () => {
  const GROUP_NAME = 'Welcome Screen Error-Path Group';
  const INVITEE_NAME = 'Erroring Erin';

  test('a fresh first-timer whose join request fails to publish sees the joinRequestError Alert above WelcomeInvite, and is not left stuck', async ({ browser }) => {
    await computeTestKeypairs();
    const { context: ctxAdmin, page: pageAdmin } = await bootUser(browser, USER_A, { nickname: 'Admin' });
    const { context: ctxInvitee, page: pageInvitee } = await bootAnonymous(browser);

    try {
      await createGroup(pageAdmin, GROUP_NAME);
      const inviteUrl = await generateInviteLink(pageAdmin, GROUP_NAME);

      const url = new URL(inviteUrl);
      const pathWithQuery = url.pathname + url.search;
      await pageInvitee.goto(pathWithQuery);
      await dismissErrorOverlay(pageInvitee);

      await expect(pageInvitee.getByTestId('welcome-invite')).toBeVisible({ timeout: 30_000 });
      const nameInput = pageInvitee.getByTestId('welcome-name-input');
      await nameInput.fill(INVITEE_NAME);
      const action = pageInvitee.getByTestId('welcome-primary-action');
      await expect(action).toBeEnabled();

      // Deterministically force sendJoinRequest's relay publish to fail: the
      // page/app is already fully loaded (identity + group data resolved
      // in memory), so cutting the context's network here only affects the
      // NEW WebSocket connections `rawPublish` opens per relay at click
      // time. Those either fail fast via `ws.onerror` or, worst case,
      // exhaust their own internal 10s per-relay timeout — either way a
      // deterministic failure, never a relay-availability-dependent flake.
      await ctxInvitee.setOffline(true);
      await action.click();

      // JoinRequestCard's welcome-variant branch renders a standalone
      // Chakra `Alert` (role="alert" by default) ABOVE `WelcomeInvite` when
      // the existing `error` state is set — not inside WelcomeInvite, which
      // has no error slot by design (S2).
      const wrapper = pageInvitee.getByTestId('join-request-welcome-wrapper');
      const errorAlert = wrapper.getByRole('alert');
      await expect(errorAlert).toBeVisible({ timeout: 15_000 });
      await expect(errorAlert).toContainText('Failed to send join request');

      // Not a dead end: the welcome screen is still there and the action is
      // clickable again — `sending` is reset in handleSendRequest's
      // `finally` branch — and no false "sent" confirmation ever appeared.
      await expect(pageInvitee.getByTestId('welcome-invite')).toBeVisible();
      await expect(action).toBeEnabled();
      await expect(pageInvitee.getByTestId('join-request-sent')).toHaveCount(0);
    } finally {
      await ctxInvitee.setOffline(false).catch(() => {});
      await ctxAdmin.close();
      await ctxInvitee.close();
    }
  });
});

// ---------------------------------------------------------------------------
// Pre-commit review gate remediation, Finding A: fresh-session first-timer
// who ALREADY has a saved nickname (e.g. from an earlier /profile edit this
// same session) must still be gated on the VISIBLE name field, not on
// `gateActive` (which is false once a shareable nickname is saved). Before
// the fix, `requestDisabled = gateActive && !hasShareableName(nameDraft)`
// evaluated to `false` regardless of the field's content whenever
// `gateActive` was false — so clearing the pre-filled field left the button
// enabled and a blank `requesterName` could be sent (AC-GROUP-3, AC-NAME-1
// violation).
// ---------------------------------------------------------------------------
test.describe('Group-invite welcome screen — fresh session, already-named first-timer (gate-remediation Finding A)', () => {
  const GROUP_NAME = 'Welcome Screen Already-Named Group';
  const PRIOR_NAME = 'Prior Paula';
  const FIXED_NAME = 'Fixed Fiona';

  test('a first-timer who already saved a nickname via /profile earlier THIS session sees the welcome name field gated on its own content — clearing it disables the action, and the eventual join request carries the newly-typed name, never a blank one', async ({ browser }) => {
    await computeTestKeypairs();
    const { context: ctxAdmin, page: pageAdmin } = await bootUser(browser, USER_A, { nickname: 'Admin' });
    const { context: ctxInvitee, page: pageInvitee } = await bootAnonymous(browser);

    try {
      await createGroup(pageAdmin, GROUP_NAME);
      const inviteUrl = await generateInviteLink(pageAdmin, GROUP_NAME);
      const url = new URL(inviteUrl);
      const pathWithQuery = url.pathname + url.search;

      // First navigation for this anonymous context: auto-generates the
      // identity and establishes isFreshIdentity=true for this SPA session
      // (S1's seam — computed once at NostrIdentityProvider mount, which
      // persists across client-side route changes within the same tab).
      await pageInvitee.goto(pathWithQuery);
      await dismissErrorOverlay(pageInvitee);
      await expect(pageInvitee.getByTestId('welcome-invite')).toBeVisible({ timeout: 30_000 });
      await expect(pageInvitee.getByTestId('join-request-card')).toHaveCount(0);

      // Set a nickname through the app's OWN profile-edit flow (never a raw
      // storage write) via a CLIENT-SIDE navigation (header-profile-chip is
      // a NextLink) so the identity Provider never remounts and
      // isFreshIdentity stays true in memory, exactly as it would for a
      // real visitor who edited their profile earlier in the same tab.
      await pageInvitee.getByTestId('header-profile-chip').click();
      await expect(pageInvitee.getByTestId('profile-page')).toBeVisible({ timeout: 15_000 });
      const nicknameInput = pageInvitee.getByTestId('profile-nickname-input');
      await nicknameInput.fill(PRIOR_NAME);
      await expect.poll(() => readSavedNickname(pageInvitee)).toBe(PRIOR_NAME);

      // Client-side back navigation (browser back), not a full reload —
      // proven by the assertion right below: if this were a full reload,
      // isFreshIdentity would re-derive to false (identity now on disk) and
      // the OLD inline join-request-card would render instead of
      // welcome-invite.
      await pageInvitee.goBack();
      await dismissErrorOverlay(pageInvitee);
      await expect(pageInvitee.getByTestId('welcome-invite')).toBeVisible({ timeout: 15_000 });
      await expect(pageInvitee.getByTestId('join-request-card')).toHaveCount(0);

      // The visible field is pre-filled from the now-saved nickname —
      // gateActive is false here (a shareable name IS saved), which is
      // exactly the condition Finding A's bug required.
      const nameInput = pageInvitee.getByTestId('welcome-name-input');
      const action = pageInvitee.getByTestId('welcome-primary-action');
      await expect(nameInput).toHaveValue(PRIOR_NAME);
      await expect(action).toBeEnabled();

      // THE FIX: clearing the pre-filled field must disable the action even
      // though gateActive is false. Pre-fix, this stayed enabled.
      await nameInput.fill('');
      await expect(action).toBeDisabled();

      // Typing a fresh name re-enables it.
      await nameInput.fill(FIXED_NAME);
      await expect(action).toBeEnabled();

      await action.click();
      await expect(pageInvitee.getByTestId('join-request-sent')).toBeVisible({ timeout: 30_000 });

      // The saved nickname reflects the edited (typed) name, not the stale
      // PRIOR_NAME and never blank — proves the save-on-submit path uses
      // the visible field, not `gateActive`.
      await expect.poll(() => readSavedNickname(pageInvitee)).toBe(FIXED_NAME);

      // Admin sees the real, non-blank requesterName end to end — proves the
      // fix isn't just a UI-only disable but that no blank requesterName was
      // ever transmitted (AC-GROUP-3/AC-NAME-1's actual invariant). Reuses
      // the SAME admin session already open above (no relay-timing gap from
      // a fresh boot). Mirrors the AC-GROUP-1..4 test's notification-badge
      // poll above to avoid a relay-propagation race.
      await pageAdmin.goto('/groups/');
      await expect(
        pageAdmin.getByTestId('groups-empty-state').or(pageAdmin.getByTestId('groups-list')),
      ).toBeVisible({ timeout: 60_000 });
      await expect
        .poll(
          async () => {
            await dismissErrorOverlay(pageAdmin);
            const badge = pageAdmin.getByTestId('notification-badge').first();
            return badge.isVisible();
          },
          { timeout: 60_000, intervals: [3_000, 5_000, 5_000, 5_000, 5_000, 5_000, 5_000] },
        )
        .toBe(true);
      await openGroupDetail(pageAdmin, GROUP_NAME);
      await expect(
        pageAdmin.locator('[data-testid^="pending-request-row-"]').filter({ hasText: FIXED_NAME }),
      ).toBeVisible({ timeout: 30_000 });
    } finally {
      await ctxAdmin.close();
      await ctxInvitee.close();
    }
  });
});
